### ISSUE TITLE
looking for someone to make a subcommand handler

### ISSUE THREAD

**Issue by Twi5TeD** [Twi5TeD/PlayTime#10]
if any developer wants to make a pull request to help me out that would be great :)

looking for a subcommand handler so that i can have the commands set as 
/playtime (shows help message)
/playtime <name> (shows player's playtime)
/playtime reload (reloads the config)
/playtime uptime (shows server uptime)

thanks for reading :)

**Comment by ItsLiyua** [comment]
Still looking for a subcommand handler? I'd be willing to try to make one.

**Comment by Twi5TeD** [comment]
yes sure :)

**Comment by The-Epic** [comment]
Only over a year later, did that ever get done? I would be happy to make a PR adding it

**Comment by Twi5TeD** [comment]
I've not had time but sure if you can you could thanks

**Comment by The-Epic** [comment]
PR #27 should be ready to be approved and then it should all be working

**Comment by Twi5TeD** [comment]
thanks :)
