### ISSUE TITLE
Installed plugin on a 1.18.1 Server and my whole chat got spammed with "[Server] hey AlexanderOF 1"

### ISSUE THREAD

**Issue by AlexanderOFGR** [Twi5TeD/PlayTime#18]
After removing the plugin from my server, everything is working great. Reproduce by doing: 

1) Install the plugin on a Paper Spigot Server 1,18.1
2) Join on the server

After leaving and joining again, it stops. But it does that for every player that joins for the first time...

**Comment by Twi5TeD** [comment]
nothing todo with my plugin
