### ISSUE TITLE
FileNotFoundException - /PlayTime/userdata.json

### ISSUE THREAD

**Issue by somekoder** [Twi5TeD/PlayTime#19]
`22.01 19:24:12 [Server] WARN java.io.FileNotFoundException: plugins/PlayTime/userdata.json (Too many open files)
22.01 19:24:12 [Server] WARN at java.base/java.io.FileInputStream.open0(Native Method)
22.01 19:24:12 [Server] WARN at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
22.01 19:24:12 [Server] WARN at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
22.01 19:24:12 [Server] WARN at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
22.01 19:24:12 [Server] WARN at java.base/java.io.FileReader.<init>(FileReader.java:60)
22.01 19:24:12 [Server] WARN at PlayTime.jar//me.F64.PlayTime.Commands.PlaytimeTop.getTopTen(PlaytimeTop.java:63)
22.01 19:24:12 [Server] WARN at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.get(Expansion.java:59)
22.01 19:24:12 [Server] WARN at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.onPlaceholderRequest(Expansion.java:95)
22.01 19:24:12 [Server] WARN at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:35)
22.01 19:24:12 [Server] WARN at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161)
22.01 19:24:12 [Server] WARN at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.api.util.Placeholders.setPlaceholderAPIPlaceholders(Placeholders.java:46)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.api.util.Placeholders.replace(Placeholders.java:26)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.api.util.Placeholders.replace(Placeholders.java:13)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.trait.HologramTrait.run(HologramTrait.java:225)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:491)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:359)
22.01 19:24:12 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.k(EntityHumanNPC.java:493)
22.01 19:24:12 [Server] WARN at net.minecraft.server.level.WorldServer.a(WorldServer.java:1128)
22.01 19:24:12 [Server] WARN at net.minecraft.world.level.World.a(World.java:970)
22.01 19:24:12 [Server] WARN at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:670)
22.01 19:24:12 [Server] WARN at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
22.01 19:24:12 [Server] WARN at net.minecraft.server.level.WorldServer.a(WorldServer.java:650)
22.01 19:24:12 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1607)
22.01 19:24:12 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
22.01 19:24:12 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
22.01 19:24:12 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
22.01 19:24:12 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
22.01 19:24:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)`

I'm seeing this crash in my console logs, it repeats itself over and over. Not too sure how to reproduce
I am using Playtime with Citizens

**Comment by Twi5TeD** [comment]
Delete userdata and let it regenerate

**Comment by somekoder** [comment]
Alright, it looks alright right now though I am the only person on the server. I'll let a few people join and leave and close the issue later on if it looks good :) Thanks for you help and quick reply

**Comment by somekoder** [comment]
Actually, it just happened again... Very strange

**Comment by Twi5TeD** [comment]
Check placeholderapi folder and expansions for playtime expansion if there's one delete it

**Comment by somekoder** [comment]
Just checked, I don't seem to have a playtime expansion, I have mcmmo, player, vault, luckperms and essentials

**Comment by Twi5TeD** [comment]
Can you try delete playtime plugin and redownload it please

**Comment by somekoder** [comment]
Sure no problem, I tried what you suggested and it even seems to happen with a clean slate

**Comment by somekoder** [comment]
![Exception](https://user-images.githubusercontent.com/49205285/150654030-a010bcaa-8abd-40a6-a44e-ed1f952ed5c4.PNG)

**Comment by Twi5TeD** [comment]
Are you on latest placeholderapi

**Comment by Twi5TeD** [comment]
Also is there a userdata.json file generating in playtime folder? If so open it and paste what's in it

**Comment by somekoder** [comment]
Yes, `2.11.1`

**Comment by somekoder** [comment]
Here's userdata.jon:
`[{"joins":355,"lastName":"Bendins","session":419049,"time":419049,"uuid":"e9aeb0e9-27d9-4878-b51a-a3719ab632dc"}]`

**Comment by Twi5TeD** [comment]
Hmm atm I'm really not sure why it's doing that error as it seems to all be working can you try stopping server and deleting userdata.json if you haven't done that yet

**Comment by somekoder** [comment]
Yep I've tried that, I tried this plugin a couple months ago and ran into a similar repeating error message related to corrupted player data files (I don't think it was the same though). Maybe there's a conflict with something I have setup on my server, not too sure :/

Kind of a shame because your leaderboard placeholders are awesome :')

**Comment by Twi5TeD** [comment]
not sure about it sorry if i can ill still look more into it
