### ISSUE TITLE
Unexpected token END OF FILE

### ISSUE THREAD

**Issue by ghost** [Twi5TeD/PlayTime#20]
>.... [14:31:30 INFO]: lukeja lost connection: Disconnected
>.... [14:31:30 WARN]: Unexpected token END OF FILE at position 65536.
>.... [14:31:30 WARN]: at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
>.... [14:31:30 WARN]: at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
>.... [14:31:30 WARN]: at PlayTime.jar//me.F64.PlayTime.Commands.PlaytimeTop.getTopTen(PlaytimeTop.java:64)
>.... [14:31:30 WARN]: at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.get(Expansion.java:59)
>.... [14:31:30 WARN]: at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.onPlaceholderRequest(Expansion.java:95)
>.... [14:31:30 WARN]: at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
>.... [14:31:30 WARN]: at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161)
>.... [14:31:30 WARN]: at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
>.... [14:31:30 WARN]: at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:23)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:278)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.updateAnimations(HologramLine.java:404)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$updateAnimations$6(Hologram.java:392)
>.... [14:31:30 WARN]: at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimations(Hologram.java:392)
>.... [14:31:30 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimationsAll(Hologram.java:398)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:216)
>.... [14:31:30 WARN]: at DecentHolograms-2.2.7.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
>.... [14:31:30 WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
>.... [14:31:30 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>.... [14:31:30 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>.... [14:31:30 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>.... [14:31:30 WARN]: java.lang.ArithmeticException
>.... [14:31:30 INFO]: - lukeja

**Comment by markaabo** [comment]
I have the same problem, hope it can be fixed soon @Twi5TeD

**Comment by Twi5TeD** [comment]
what version mc are you on?
what version of playtime?
what version of placeholderapi?
also post your hologram that your trying to display
also can you post your userdata.json inside of playtime folder

**Comment by PetyXbron** [comment]
I have the same issue!
### **https://srcshare.io/?id=6257de64033d2e0f76f202f5**
Under tab **Code** is the hologram yaml code and under **Error** there's my console error, when player leaves server
Very similar issue also crashes my server sometimes and takes my server to a strange state (Timed Out Error for players) and the solution is to stop the server and then kill it and start again.

> what version mc are you on? what version of playtime? what version of placeholderapi? also post your hologram that your trying to display also can you post your userdata.json inside of playtime folder

@Twi5TeD, I am using **`git-Purpur-1566 (MC: 1.18.1)*`**, **PlayTime 3.3**, **DecentHolograms 2.3.1**, **PlaceHolderAPI 2.11.1**.
You can find my yaml edited hologram code [here](https://srcshare.io/?id=6257de64033d2e0f76f202f5).
I can send you `userdata.json`, but only privately because of safety.

**Comment by Twi5TeD** [comment]
> I have the same issue!
> 
> ### **https://srcshare.io/?id=6257de64033d2e0f76f202f5**
> Under tab **Code** is the hologram yaml code and under **Error** there's my console error, when player leaves server Very similar issue also crashes my server sometimes and takes my server to a strange state (Timed Out Error for players) and the solution is to stop the server and then kill it and start again.
> 
> > what version mc are you on? what version of playtime? what version of placeholderapi? also post your hologram that your trying to display also can you post your userdata.json inside of playtime folder
> 
> @Twi5TeD, I am using **`git-Purpur-1566 (MC: 1.18.1)*`**, **PlayTime 3.3**, **DecentHolograms 2.3.1**, **PlaceHolderAPI 2.11.1**. You can find my yaml edited hologram code [here](https://srcshare.io/?id=6257de64033d2e0f76f202f5). I can send you `userdata.json`, but only privately because of safety.

Theres nothing in the userdata.json that needs to be private can you send us that also

**Comment by PetyXbron** [comment]
@Twi5TeD ***https://gist.github.com/PetyXbron/386fc392000d09ce4c480c038c43dd4c***

Names and UUIDs of players are hidden. I hope this data doesn't crash the server process. Also note, we are using Geyser - `2.0.1-SNAPSHOT (git-master-a435288)` that creates special UUIDs for Bedrock players. Something like `00000000-0000-0000-0009-01fff3b2e9ng`

**Comment by Twi5TeD** [comment]
Can you make a backup of the userdata while server is offline and delete it and restart server and see if it still happens

**Comment by PetyXbron** [comment]
> Can you make a backup of the userdata while server is offline and delete it and restart server and see if it still happens

Okay, I did it, as you said. `userdata.json` now saves from the very beginning. My hologram leaderboard had reset, but after every new join/leave of players, it will load and load. The console looks OK now. If I will notice some error with this plugin, I will report it here. Now let's wait some time if the problem will show again.
