### ISSUE TITLE
PAPI Playtime Error

### ISSUE THREAD

**Issue by RupertDeRuyver** [Twi5TeD/PlayTime#6]
I've been trying to display the player's own playtime in the TAB menu. I use the TAB plugin for this but it has always worked fine for me. The amount of logins works fine but the actual playtime gives an error. The server is 1.16.5 Spigot. (Expansion-PlayTime.jar is installed in the PAPI expansions)

This is what I put into the  TAB config:
`'&1Playtime: &9%playtime_time% &r&c&k|&r &5Amount of Logins: &d%playtime_timesjoined%'`

And this is the error I get:
`08.03.2021 - 13:34:07 - [TAB v2.8.10] PlaceholderAPI v2.10.9 generated an error when setting placeholder %playtime_time% for player KillsT3aler69
08.03.2021 - 13:34:07 - java.lang.NoSuchFieldError: PLAY_ONE_TICK
08.03.2021 - 13:34:07 -        at me.F64.papiexpansions.playtime.ExpansionPlayTime.onPlaceholderRequest(ExpansionPlayTime.java:40)
08.03.2021 - 13:34:07 -        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31)
08.03.2021 - 13:34:07 -        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
08.03.2021 - 13:34:07 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
08.03.2021 - 13:34:07 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:206)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:182)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:22)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.shared.features.PlaceholderManager.onJoin(PlaceholderManager.java:208)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:175)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:36)
08.03.2021 - 13:34:07 -        at me.neznamy.tab.shared.cpu.CPUManager$3.run(CPUManager.java:96)
08.03.2021 - 13:34:07 -        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
08.03.2021 - 13:34:07 -        at java.util.concurrent.FutureTask.run(Unknown Source)
08.03.2021 - 13:34:07 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
08.03.2021 - 13:34:07 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
08.03.2021 - 13:34:07 -        at java.lang.Thread.run(Unknown Source)`

**Comment by Twi5TeD** [comment]
fixed download the new plugin update you no longer need the expansion either as its built in thanks
